# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QStandardItemModel,QIcon
from PyQt5.QtWidgets import QHeaderView
from ui.MultiSelectComboBox import MultiSelectComboBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 518)
        MainWindow.setWindowIcon(QIcon('ui/ico_camera.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.cameraLabel = QtWidgets.QLabel()




        # self.ComboDevices = QtWidgets.QComboBox(self.centralwidget)
        self.ComboDevices = MultiSelectComboBox(self.centralwidget)
        # self.ComboDevices.addAction
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboDevices.sizePolicy().hasHeightForWidth())
        self.ComboDevices.setSizePolicy(sizePolicy)
        self.ComboDevices.setMinimumSize(QtCore.QSize(580, 20))
        self.ComboDevices.setObjectName("ComboDevices")
        # self.verticalLayout_3.addWidget(self.ComboDevices)



        self.gridLayout_3 = QtWidgets.QHBoxLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        # self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.addWidget(self.cameraLabel)
        self.gridLayout_3.addWidget(self.ComboDevices)
        self.gridLayout_3.setStretch(0,1)
        self.gridLayout_3.setStretch(1,30)
        
        self.verticalLayout_3.addLayout(self.gridLayout_3)


        self.pictureView = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureView.sizePolicy().hasHeightForWidth())
        self.pictureView.setSizePolicy(sizePolicy)
        self.pictureView.setMinimumSize(QtCore.QSize(580, 448))
        self.pictureView.setStyleSheet("background-color: black")
        self.pictureView.setText("")
        self.pictureView.setScaledContents(True)
        self.pictureView.setObjectName("pictureView")
        self.verticalLayout_3.addWidget(self.pictureView)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupCamera = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupCamera.sizePolicy().hasHeightForWidth())
        self.groupCamera.setSizePolicy(sizePolicy)
        self.groupCamera.setObjectName("groupCamera")
        self.gridLayout = QtWidgets.QGridLayout(self.groupCamera)
        self.gridLayout.setObjectName("gridLayout")
        self.bnOpen = QtWidgets.QPushButton(self.groupCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bnOpen.sizePolicy().hasHeightForWidth())
        self.bnOpen.setSizePolicy(sizePolicy)
        self.bnOpen.setObjectName("bnOpen")
        self.gridLayout.addWidget(self.bnOpen, 2, 0, 1, 1)
        self.bnEnum = QtWidgets.QPushButton(self.groupCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bnEnum.sizePolicy().hasHeightForWidth())
        self.bnEnum.setSizePolicy(sizePolicy)
        self.bnEnum.setObjectName("bnEnum")
        self.gridLayout.addWidget(self.bnEnum, 0, 0, 1, 2)
        self.bnClose = QtWidgets.QPushButton(self.groupCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bnClose.sizePolicy().hasHeightForWidth())
        self.bnClose.setSizePolicy(sizePolicy)
        self.bnClose.setObjectName("bnClose")
        self.gridLayout.addWidget(self.bnClose, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupCamera, 1, 0, 1, 1)
       

        self.groupDetect = QtWidgets.QGroupBox(self.centralwidget)
        self.groupDetect.setObjectName("groupDetect")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupDetect)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.modelLabel = QtWidgets.QLabel(self.centralwidget)
        self.gridLayout_2.addWidget(self.modelLabel, 0, 0, 1, 1)
        
        self.ComboModels = QtWidgets.QComboBox(self.centralwidget)
        self.ComboModels.setObjectName("comModels")
        self.gridLayout_2.addWidget(self.ComboModels, 0, 1, 1, 3)

        self.bnStart = QtWidgets.QPushButton(self.groupDetect)
        self.bnStart.setObjectName("bnStart")
        self.gridLayout_2.addWidget(self.bnStart, 1, 0, 1, 4)

        self.bnStop = QtWidgets.QPushButton(self.groupDetect)
        self.bnStop.setObjectName("bnStop")
        self.gridLayout_2.addWidget(self.bnStop, 2, 0, 1, 4)

        self.gridLayout_5.addWidget(self.groupDetect, 2, 0, 1, 1)
        self.groupResult = QtWidgets.QGroupBox(self.centralwidget)
        self.groupResult.setObjectName("groupResult")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupResult)
        self.verticalLayout_13.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.resultTable = QtWidgets.QTableView(self.groupResult)
        self.resultTable.setAutoScrollMargin(16)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.horizontalHeader().setSortIndicatorShown(False)
        self.resultTable.verticalHeader().setSortIndicatorShown(False)
        self.resultTable.verticalHeader().setVisible(False)

        
        
        self.resultModel=QStandardItemModel(0,3)
        #设置水平方向四个头标签文本内容
        self.resultModel.setHorizontalHeaderLabels(['检测任务','梁编号','气泡数','裂缝数'])
        self.resultTable.setModel(self.resultModel)
        self.resultTable.setColumnWidth(0, 60) 
        self.resultTable.setColumnWidth(1, 60) 
        self.resultTable.setColumnWidth(2, 60)
        self.resultTable.setColumnWidth(3, 60)
        
        # #水平方向标签拓展剩下的窗口部分，填满表格
        self.resultTable.horizontalHeader().setStretchLastSection(True)
        # #水平方向，表格大小拓展到适当的尺寸      
        self.resultTable.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.resultTable.horizontalHeader().setMinimumSectionSize(60)
        self.resultTable.horizontalHeader().setSectionResizeMode(0, QHeaderView.Interactive)
        self.resultTable.horizontalHeader().setSectionResizeMode(1, QHeaderView.Interactive)
        self.resultTable.horizontalHeader().setSectionResizeMode(2, QHeaderView.Interactive)
        # self.resultTable.setItemDelegate()

        self.verticalLayout_13.addWidget(self.resultTable)
        self.gridLayout_5.addWidget(self.groupResult, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout_2.setStretch(0, 20)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        # 初始化控件状态
        self.groupDetect.setEnabled(False)

        self.bnOpen.setEnabled(False)
        self.bnClose.setEnabled(False)

        self.bnStart.setEnabled(False)
        self.bnStop.setEnabled(False)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "预制梁外观质量缺陷检测"))
        self.cameraLabel.setText(_translate("MainWindow", "相机列表"))
        self.groupCamera.setTitle(_translate("MainWindow", "相机控制"))
        self.bnOpen.setText(_translate("MainWindow", "打开相机"))
        self.bnEnum.setText(_translate("MainWindow", "查找相机"))
        self.bnClose.setText(_translate("MainWindow", "关闭相机"))
        self.modelLabel.setText(_translate("MainWindow", "选择模型"))
        self.groupDetect.setTitle(_translate("MainWindow", "图像检测"))
        self.bnStart.setText(_translate("MainWindow", "开始检测"))
        self.bnStop.setText(_translate("MainWindow", "停止检测"))
        self.groupResult.setTitle(_translate("MainWindow", "检测记录"))
